-- =========================================================
-- SKILL-BUILD
-- Course Enrollments
-- =========================================================

create table if not exists public.enrollments (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    course_id bigint not null
        references public.courses(id)
        on delete cascade,

    enrolled_at timestamptz not null
        default now(),

    unique (user_id, course_id)
);


create index if not exists enrollments_user_id_idx
on public.enrollments(user_id);


create index if not exists enrollments_course_id_idx
on public.enrollments(course_id);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.enrollments
enable row level security;


drop policy if exists "Users can view their own enrollments"
on public.enrollments;

create policy "Users can view their own enrollments"
on public.enrollments
for select
to authenticated
using (
    auth.uid() = user_id
);


drop policy if exists "Users can create their own enrollments"
on public.enrollments;

create policy "Users can create their own enrollments"
on public.enrollments
for insert
to authenticated
with check (
    auth.uid() = user_id
);


drop policy if exists "Users can delete their own enrollments"
on public.enrollments;

create policy "Users can delete their own enrollments"
on public.enrollments
for delete
to authenticated
using (
    auth.uid() = user_id
);


-- =========================================================
-- Optional: no public access through anon
-- =========================================================

revoke all
on public.enrollments
from anon;
