-- =========================================================
-- SKILL-BUILD
-- Lesson Progress
-- =========================================================

create table if not exists public.user_progress (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    lesson_id bigint not null
        references public.lessons(id)
        on delete cascade,

    completed boolean not null default false,

    completed_at timestamptz,

    updated_at timestamptz not null default now(),

    unique (user_id, lesson_id)
);

alter table public.user_progress
    add column if not exists completed boolean not null default false;

alter table public.user_progress
    add column if not exists completed_at timestamptz;

alter table public.user_progress
    add column if not exists updated_at timestamptz not null default now();

create index if not exists user_progress_user_id_idx
on public.user_progress(user_id);

create index if not exists user_progress_lesson_id_idx
on public.user_progress(lesson_id);

alter table public.user_progress
    enable row level security;

drop policy if exists "Users can view their own lesson progress"
on public.user_progress;

create policy "Users can view their own lesson progress"
on public.user_progress
for select
 to authenticated
using (
    auth.uid() = user_id
);

drop policy if exists "Users can create their own lesson progress"
on public.user_progress;

create policy "Users can create their own lesson progress"
on public.user_progress
for insert
 to authenticated
with check (
    auth.uid() = user_id
);

drop policy if exists "Users can update their own lesson progress"
on public.user_progress;

create policy "Users can update their own lesson progress"
on public.user_progress
for update
 to authenticated
using (
    auth.uid() = user_id
)
with check (
    auth.uid() = user_id
);

revoke all
on public.user_progress
from anon;
